apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# nameSuffix: -prod
commonLabels:
labels:
  # It is essential for this label (or at least one unique label per environment)
  # to be part of selectors to ensure they are applied correctly.
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: prod
  # these labels do not need to be included in selectors,
  # but are useful for identifying the environment details
  - pairs:
      app.kubernetes.io/part-of: vacancy-management
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-prod-sced-rhp-spoke-aks
      app.kubernetes.io/environment: prod
      app.kubernetes.io/tier: prod
resources:
  - ./cronjobs.yaml
  - ./deployments.yaml
  - ./external-secrets.yaml
  - ./hpas.yaml
  - ./ingresses.yaml
  - ./services.yaml
  - ./stateful-sets.yaml
configMapGenerator:
  - name: redis
    files:
      - ./configs/redis/init.sh
      - ./configs/redis/primary.conf
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
  - name: vacman-backend
    behavior: create
    files:
      - application.yaml=./configs/vacman-backend.yaml
  - name: vacman-frontend
    behavior: create
    envs:
      - ./configs/vacman-frontend.conf
  - name: group-sync
    behavior: create
    literals:
      - DRY_RUN=false
      - LOG_LEVEL=info
      - TENANT_ID=9ed55846-8a81-4246-acd8-b1a01abfc0d1
      - CLIENT_ID=61e40073-c461-4ec8-8397-99f2976d4982
      # EDSC.F.DGSRH Equipe.SGIP ELS / PIMS SLE.Team.HRSB.F.ESDC, EDSC.F.NA.RH.SE PE / PE WS.HR.NA.F.ESDC, EDSC.F.DGRH.O EX S.Conseiller RH / HR Advisor.EX S O.HRSB.F.ESDC
      - SOURCE_GROUP_IDS=099d7edb-ca40-4c0f-99eb-8ecb4867edd7,15c621c8-0d8d-435a-b513-8d159f3fdf0d,cb182398-3dcf-4b2b-9a84-374d27afe626
      - TARGET_GROUP_ID=6a5548e2-e6d6-4c06-ae7e-260801f09de3

secretGenerator:
  - name: redis
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true
  - name: vacman-backend
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true
  - name: vacman-frontend
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true
  - name: group-sync
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true
