#######################################################################################################################
# Configuration intended to be mounted as `application-local.yaml` for the vacman-backend Spring Boot application.
#
# This file provides environment-specific overrides to the default configuration.
#######################################################################################################################

application.data-seeder.enabled: true

logging:
  level:
    '[ca.gov.dts_stn.vacman.api]': debug
    # '[org.springframework]': debug

management:
  otlp:
    metrics:
      export:
        enabled: true
        aggregation-temporality: delta
        url: https://dynatrace.dev-dp.admin.dts-stn.com/e/21a07aef-852b-4d9b-aa87-ee5f8b79f8c9/api/v2/otlp/v1/metrics

spring:
  datasource:
    url: jdbc:sqlserver://esdcvacmansqlsrv.database.windows.net;databaseName=EsDVacManDB_UAT;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.yaml
    # drop-first: true # ⚠️ ‼‼‼ NEVER SET THIS IN PROD ‼‼‼ ⚠️

application:
  gcnotify:
    generic-template-id: 9de577c3-3963-41a9-8fdb-676fcb41a1a6
    hr-gd-inbox-email: EDSC.Priorites.2-2.Priorities.ESDC@hrsdc-rhdcc.gc.ca
    pims-sle-team-email: EDSC.Priorites.2-2.Priorities.ESDC@hrsdc-rhdcc.gc.ca
  metrics:
    environment-name: uat
