#######################################################################################################################
# Configuration intended to be mounted as `application-local.yaml` for the vacman-backend Spring Boot application.
#
# This file provides environment-specific overrides to the default configuration.
#######################################################################################################################

# logging:
#   level:
#     '[ca.gov.dts_stn.vacman.api]': trace
#     '[org.springframework]': debug

management:
  otlp:
    metrics:
      export:
        enabled: true
        aggregation-temporality: delta
        url: https://dynatrace.prod-dp.admin.dts-stn.com/e/676a0299-9802-4933-99d4-481318a557db/api/v2/otlp/v1/metrics

spring:
  datasource:
    url: jdbc:sqlserver://esccprodvacmansqlsrv.database.windows.net;databaseName=EsPrdVacManSqldb;encrypt=true;trustServerCertificate=true;
  liquibase:
    contexts: prod

application:
  entra-id:
    client-id: 61e40073-c461-4ec8-8397-99f2976d4982
  gcnotify:
    generic-template-id: 52b26a60-94b7-4b07-8c4c-5cbaaf43b3af
    hr-gd-inbox-email: EDSC.Priorites.2-2.Priorities.ESDC@hrsdc-rhdcc.gc.ca
    pims-sle-team-email: EDSC.Priorites.2-2.Priorities.ESDC@hrsdc-rhdcc.gc.ca
  metrics:
    environment-name: prod
